### ISSUE TITLE
Format of dates returned to event.js (of github page)

### ISSUE THREAD

**Issue by whatjoesays** [pavlakis/notts-digital#11]
This API provides the events dates in the format: `l jS F Y at g:ia`. For example: Monday 3rd October 2016 at 6:30pm.

It would be preferable to receive it without the preformatting (e.g. use of 'at' and 12hr clock), instead sending an epoch timestamp or ISO format date that can be formatted as desired by the JS.

_Background: currently redesigning the github page and found this constraint._

**Comment by pavlakis** [comment]
I'll add another field with the raw timestamp.

**Comment by pavlakis** [comment]
A field has been added with the ISO format and has been merged into master.

Not been deployed yet.

```json

{  
   "group":"PHPMiNDS",
   "subject":"PHPSchool.io at PHPMINDS",
   "date_time":"Thursday 13th October 2016 at 7:00pm",
   "location":"JH, 34 Stoney Street, Nottingham, NG1 1NB, Nottingham",
   "event_url":"http://www.meetup.com/PHPMiNDS-in-Nottingham/events/234153982/",
   "iso_date":"2016-10-13T19:00:00+01:00"
}
```
