### ISSUE TITLE
Possible event data from Meetup

### ISSUE THREAD

**Issue by whatjoesays** [pavlakis/notts-digital#12]
_Background: currently redesigning github page_

The API currently returns date, url, location and subject for the upcoming event (as well as group name as set on Meetup).

What other information could it retrieve? For example, could it get the event description excerpt?

What options are available regarding the meetup/group? For example, could it retrieve the meetup logo?

**Comment by pavlakis** [comment]
@whatjoesays I believe the answer to most of these is yes. 
See the Meetup API for the full list: https://www.meetup.com/meetup_api/docs/2/groups/

Let me know what you need and I'll add it :)

**Comment by whatjoesays** [comment]
Let’s keep it simple to begin with. In addition to what is already sent:

**From the group:**
- `description`
- `group_photo` (which I assume is the logo)

**From the next event:**
- `description`
- `name`
- `venue`

Thanks.

**Comment by pavlakis** [comment]
Added group info section to include:

Description and Logo

https://github.com/pavlakis/notts-digital/tree/feature/display-more-event-data-from-meetup-18

**Comment by pavlakis** [comment]
Group info:

* `group_photo`
* `group_description`

Event info:

* `subject` - The event title
* `description` - The event description
*  `date_time` - Kept for BC. e.g "Thursday 12th January 2017 at 7:00pm"
*  `location` - the venue address e.g. "JH, 34a Stoney Street, Nottingham, NG1 1NB, Nottingham"
* `event_url` - e.g. "https:\/\/www.meetup.com\/PHPMiNDS-in-Nottingham\/events\/236134043\/",
* `iso_date` - e.g. "2017-01-12T19:00:00+00:00"

The `next_event` if exists will have the same structure as the current event.

As per [tag 1.0.0](https://github.com/pavlakis/notts-digital/releases/tag/1.0.0)
