### ISSUE TITLE
Broken dependency reference: dms/meetup-api-client

### ISSUE THREAD

**Issue by crossowl** [pavlakis/notts-digital#64]
The https://github.com/nitinjavakid/meetup-api-client repo (fork) has been deleted and is causing test builds to fail: https://travis-ci.org/pavlakis/notts-digital/jobs/593293647.

https://github.com/rdohms/meetup-api-client seems to be the canonical repository for this project.

Could we update the dependency please? assuming the fork hadn't diverged significantly

**Comment by pavlakis** [comment]
@crossowl thank you for opening the issue.

I can see that the main repository has merged the PR where the fork was taken from, and tagged `v2.4.0` with support for `OAuth2`

https://github.com/rdohms/meetup-api-client/releases/tag/v2.4.0

**Comment by crossowl** [comment]
Thanks :+1:
